### ISSUE TITLE
WeedMaps Update - Plugin No Longer Works

### ISSUE THREAD

**Issue by jslothower** [bmoredrew/WeedMaps-Menu-WordPress#2]
Hi!  WeedMaps recently (two weeks ago) updated their overall UI.  Unfortunately, the menu looks quite different with the new version of WeedMaps, and it doesn't seem to correlate to your plugin any longer.  Any ETA on when the plugin might be updated to work with the new WeedMaps?

**Comment by bmoredrew** [comment]
Hi, I don't have access to review the updated menu embed code, so I don't know when I'll be able to update it.

**Comment by bmoredrew** [comment]
This has been updated with the latest embed code, you can grab it from here on github or the wp repo: https://wordpress.org/plugins/weedmaps-menu-embed/
